### ISSUE TITLE
Multiple requests to auth to okta - Parallel tools

### ISSUE THREAD

**Issue by eperdeme** [godaddy/aws-okta-processor#27]
Hi,

Not sure if this is even fixable, but we use tools such as Helmsman which can run helm commands in parallel. When using such tools it will spawn the helm CLI several times, when this occurs we have to enter our Okta password/MFA prompt per thread.

Not too sure how you could if at all resolve this.

**Comment by tahoward** [comment]
Hello, that does sound very annoying. Can you try seeding the cache first? IE:

```
export AWS_PROFILE=<profile_name_using_credential_process>

# This should prompt for everything to build cache
aws sts get-caller-identity

# Run Helm et al afterwards
<cmds>
```

**Comment by eperdeme** [comment]
Hello,

It's fine if I run a single command to get the credentials and then I can run wrappers like helmsman which then work fine using the cache. It's only when the credentials are expired and it needs to reauth the issue occurs.

It's not a major problem.
