### ISSUE TITLE
processor should not just hang if it's out of date.

### ISSUE THREAD

**Issue by stevestarck** [godaddy/aws-okta-processor#3]
spent a good deal of time debugging why the processor was hanging.  tiurns out i was on 0.11 or something like that.  would be better if the processor told you that it was out of date instead of just hanging.

**Comment by tahoward** [comment]
Hang has been resolved with inclusion of https://github.com/godaddy/aws-okta-processor/blob/f28a0963becdcd960f18a7fd52ff229a57e68440/src/aws_okta_processor/core/fetcher.py#L43-L49 in initial public release.
