### ISSUE TITLE
Prompt for user name

### ISSUE THREAD

**Issue by StefanoDeVuono** [godaddy/aws-okta-processor#30]
Currently if I try to authenticate without passing a username, aws-okta-processor will just pass `None` as the user name to `get_okta_single_use_token`.

I'd prefer it prompt me for input (just as it does for password). Is this a feature that people would be interested in?

**Comment by StefanoDeVuono** [comment]
@tahoward Very cool. I was going to post up something myself, but it looks like you've already gotten to it (and with org to boot!).

Am I allowed to review the PR?

**Comment by tahoward** [comment]
Resolved with release:
https://github.com/godaddy/aws-okta-processor/releases/tag/v1.5.2
