### ISSUE TITLE
no default region is exported

### ISSUE THREAD

**Issue by delbao11** [godaddy/aws-okta-processor#37]
aws-okta-processor authenticate --environment --user XXX --organization XXX -R us-east-1 --no-okta-cache --no-aws-cache

but only AWS key is exported to environment variable, not the AWS_DEFAULT_REGION 

What is the use of -R?

**Comment by tahoward** [comment]
If for some reason AWS STS API is having issues for a specific region you can force communication to occur on another region. I have personally never had to set region since STS has always worked with the region it defaults to. Also be aware IAM Roles are not regionally scoped.
